#602
version: 0.0
os: linux
files:
    - source: /
      destination: /home/ubuntu/build/
    - source: /
      destination: /var/www/html/

permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu

hooks:
  BeforeInstall:
    - location: ../../../../../../home/ubuntu/scripts/beforeInstall.bash