#602
version: 0.0
os: linux
files:
    - source: /
      destination: /home/ubuntu/build/
    - source: /
      destination: /var/www/html/  
    # - source: /index.html
    #   destination: /var/www/html/index.html
    #- source: /elaviz_css.css
    #  destination: /var/www/html/elaviz_css.css

permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu

hooks:
  BeforeInstall:
    - location: ../../../../../../home/ubuntu/scripts/beforeInstall.bash